name: portal
description: "TicketX mobile application"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
#flutter: Request Body: {"email":"batkhuunomindari@gmail.com","password":"Nasanjargal85@"}
# flutter run -d macos
version: 1.0.19+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  overlay_support: ^2.1.0
  textstyle_extensions: ^2.0.0-nullsafety
  page_transition: ^2.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  http: ^1.3.0
  flutter_easyloading: ^3.0.5
  intl: ^0.20.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.0+1
  pinput: ^4.0.0
  skeletonizer: ^2.1.0+1
  flutter_animate: ^4.5.0
  flutter_gallery_3d: ^1.1.1
  weather: ^3.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.2.6
  pull_to_refresh: ^2.0.0
  zoom_tap_animation: ^1.1.0
  # share_plus: ^10.1.4
  # swipeable_page_route: ^0.4.3
  animated_icon: ^0.0.9
  palette_generator: ^0.3.3+3
  loading_animation_widget: ^1.2.1
  flutter_sticky_header: ^0.6.5
  blurrycontainer: ^2.1.0
  path_drawing: ^1.0.1
  xml: ^6.5.0
  interactable_svg: ^0.0.7
  qr_flutter: ^4.1.0
  path_provider: ^2.0.11
  permission_handler: ^12.0.0
  # webview_flutter_android: ^4.3.4
  # webview_flutter_wkwebview: ^3.18.5
  # webview_flutter: ^4.10.0
  app_settings: ^5.1.1
  carousel_slider: ^5.0.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  infinite_scroll_pagination: ^4.0.0
  flutter_speed_dial: ^7.0.0
  jwt_decoder: ^2.0.1
  shimmer: ^3.0.0
  supercharged: any
  simple_animations: ^3.1.1
  confetti: ^0.8.0
  flutter_quill: ^11.4.2
  snow_fall_animation: ^0.0.1+2
  pay: ^3.1.0
  local_auth: ^2.3.0
  package_info_plus: ^8.3.0
  zo_animated_border: ^0.0.6
  audioplayers: ^6.4.0
  flutter_thermal_printer: ^1.2.4
  flutter_inappwebview: ^6.1.5
  

  # firebase_core: ^3.13.0
  # firebase_messaging: ^15.2.5
  # firebase_remote_config: ^5.4.3
  # firebase_performance: ^0.10.1+5
  # firebase_crashlytics: ^4.3.5
  # firebase_analytics: ^11.4.5
  # flutter_local_notifications: ^19.3.0

  

#   amplify_flutter: ^2.6.0
#   amplify_auth_cognito: ^2.6.0
#   amplify_authenticator: ^2.3.2
#   amazon_cognito_identity_dart_2: ^3.8.1
#   flutter_facebook_auth: ^7.1.1

  app_links: ^6.4.0
  msix: ^3.16.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0 

flutter:

  uses-material-design: true

  assets:
    - lib/language/en.json
    - lib/language/mn.json
    - assets/images/
    - assets/images/app/
    - assets/images/component/
    - assets/images/dump/
    - assets/sound/csgo-open.mp3
    - assets/sound/csgo-spin.mp3
    - assets/sound/csgo-end.mp3
    - lib/screens/cart/merch/city.json
    - lib/screens/cart/merch/district.json
    - lib/screens/cart/merch/quarter.json



    - shorebird.yaml



  fonts:
    - family: Zona Pro
      fonts:
        - asset: assets/font/ZonaPro-Light.ttf
          weight: 300
        - asset: assets/font/ZonaPro-LightItalic.ttf
          weight: 300
        - asset: assets/font/ZonaPro-Regular.ttf
          weight: 400
        - asset: assets/font/ZonaPro-SemiBold.ttf
          weight: 500
        - asset: assets/font/ZonaPro-SemiBoldItalic.ttf
          weight: 500
        - asset: assets/font/ZonaPro-Bold.ttf
          weight: 700
        - asset: assets/font/ZonaPro-BoldItalic.ttf
          weight: 700
